apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitdi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jitdi
  template:
    metadata:
      labels:
        app: jitdi
    spec:
      containers:
      - name: jitdi
        image: ghcr.io/wzshiming/jitdi/jitdi:v0.0.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
      serviceAccountName: jitdi
      restartPolicy: Always
